### ISSUE TITLE
> I love you

### ISSUE THREAD

**Issue by HeyItsMicro** [Physuru/fwdhttpsd#5] opened 2021-10-03 03:44 UTC
> I love you

Micro you are a Author. How good is it

_Originally posted by @Physuru in https://github.com/Physuru/fwdhttpsd/issues/2#issuecomment-932856217_

**Comment by HeyItsMicro** [comment] 2021-10-03 03:44
I LOVE BEING AN AUTHOR!! SO GOOOD

**Comment by Physuru** [comment] 2021-10-03 03:45
- [ ] haha theres a fuccin checkbox

**Comment by HeyItsMicro** [comment] 2021-10-03 03:47
> [x] haha theres a fuccin checkbox

LMFAO WHAT? !

**Comment by itss0n1c** [comment] 2021-10-03 03:51
Duplicate of #2

**Comment by Physuru** [comment] 2021-10-04 23:15
> > I love you
thanks

**Closed** 2021-10-09 04:18 UTC
